import * as assert from 'assert';
import { isWsl, getWslHostIp } from '../../shared/utils/wsl';

suite('WSL Utilities Test Suite', () => {

    suite('isWsl', () => {
        test('should return true when platform is linux and version string contains "microsoft"', () => {
            const isWslEnvironment = isWsl('linux', () => '5.10.102.1-microsoft-standard-WSL2');
            assert.strictEqual(isWslEnvironment, true);
        });

        test('should return true when platform is linux and version string contains "wsl"', () => {
            const isWslEnvironment = isWsl('linux', () => '5.10.102.1-WSL2');
            assert.strictEqual(isWslEnvironment, true);
        });

        test('should return false when platform is linux but version string is generic', () => {
            const isWslEnvironment = isWsl('linux', () => '5.4.0-109-generic');
            assert.strictEqual(isWslEnvironment, false);
        });

        test('should return false when platform is not linux', () => {
            const isWslEnvironment = isWsl('darwin', () => 'Darwin Kernel Version 21.6.0');
            assert.strictEqual(isWslEnvironment, false);
        });

        test('should return false when version reading fails', () => {
            const isWslEnvironment = isWsl('linux', () => { throw new Error('File not found'); });
            assert.strictEqual(isWslEnvironment, false);
        });
    });

    suite('getWslHostIp', () => {
        test('should extract nameserver IPv4 address', () => {
            const mockResolvConf = `# This file was automatically generated by WSL.
nameserver 172.19.16.1
`;
            const ip = getWslHostIp(() => mockResolvConf);
            assert.strictEqual(ip, '172.19.16.1');
        });

        test('should extract first nameserver if multiple exist', () => {
            const mockResolvConf = `
nameserver 192.168.1.1
nameserver 8.8.8.8
`;
            const ip = getWslHostIp(() => mockResolvConf);
            assert.strictEqual(ip, '192.168.1.1');
        });

        test('should return null if nameserver is missing', () => {
            const mockResolvConf = `# No nameserver here
options timeout:1
`;
            const ip = getWslHostIp(() => mockResolvConf);
            assert.strictEqual(ip, null);
        });

        test('should return null if file reading fails', () => {
            const ip = getWslHostIp(() => { throw new Error('File not found'); });
            assert.strictEqual(ip, null);
        });

        test('should return null for 10.255.255.254 (WSL2 Mirrored Mode DNS)', () => {
            // 10.255.255.254 is the DNS resolver in WSL2 Mirrored Networking Mode,
            // not a valid Host IP for connecting to Windows services.
            const mockResolvConf = `# Generated by WSL (Mirrored Mode)
nameserver 10.255.255.254
`;
            const ip = getWslHostIp(() => mockResolvConf);
            assert.strictEqual(ip, null, 'Should filter out 10.255.255.254 as it is not a valid Host IP');
        });
    });
});
